"""Eq. 88, measured along the TRUE gauge direction.

Every frozen constant carries the bond gauge on two kinds of index: the new
bond (chi) and the fused cut leg n = chi*d2.  With a global unitary
W = exp(tX), X anti-Hermitian,

    U*      -> kron(W,I)' U* W          dU*      = U* X - kron(X,I) U*
    U_perp  -> kron(W,I)' U_perp        dU_perp  =      - kron(X,I) U_perp
    Vh*     -> W' Vh* kron(W,I)         dVh*     = Vh* kron(X,I) - X Vh*
    Vh_perp -> Vh_perp kron(W,I)        dVh_perp = Vh_perp kron(X,I)
    s*inv   -> W' s*inv W               ds*inv   = [s*inv, X]

Projecting onto `U* X` alone (as an earlier pass did) drops the kron(X,I)
pieces and therefore does not measure a gauge direction at all.
"""

import sys

import jax
import jax.numpy as jnp

jax.config.update("jax_enable_x64", True)
sys.path.insert(0, "/home/yjkao/tenax/tests")

from test_ctm_root_implicit_asym import _gate, _site_tensor  # noqa: E402

import tenax.algorithms._ctm_root_implicit_asym as M  # noqa: E402
from tenax.algorithms._ctm_c4v_root_implicit import _solve_root_adjoint  # noqa: E402
from tenax.algorithms._ctm_tensor_init import initialize_ctm_tensor_env  # noqa: E402
from tenax.core.tensor import DenseTensor  # noqa: E402

A = _site_tensor()
chi = 4
gate = _gate(1.0)
A_data = A.todense()

env, a_arr, _meta = M.converge(A, chi, max_iter=300, conv_tol=1e-13)
root, res = M.asym_root_parametrize(env, a_arr, chi, polish_steps=30)
root_cov = M.asym_root_to_covariant_convention(root)
S_star = root_cov.s
tilde = M.remove_inverse_roots(root_cov.env, S_star)
y_star = (tilde, root_cov.u, S_star, root_cov.v)
template = initialize_ctm_tensor_env(A, chi)
d2 = a_arr.shape[0]
n = chi * d2
print(f"root residual {res:.3e}   chi={chi} d2={d2} n={n}")


def energy_of(a_data, env_tilde, S_all):
    A_live = DenseTensor(a_data, A.indices)
    return M.asym_energy(
        A_live, M.absorb_inverse_roots(env_tilde, S_all), template, gate
    )


energy, vjp_energy = jax.vjp(energy_of, A_data, tilde, S_star)
grad_direct, tilde_bar, S_bar = vjp_energy(jnp.ones((), dtype=energy.dtype))

# --- calibrate the cotangent pairing against a finite difference ---------
key = jax.random.PRNGKey(3)
dA = jax.random.normal(key, A_data.shape, dtype=A_data.dtype)
dA = dA / jnp.linalg.norm(dA)
h = 1e-6
fd = float(
    (
        energy_of(A_data + h * dA, tilde, S_star)
        - energy_of(A_data - h * dA, tilde, S_star)
    )
    / (2 * h)
)
p_plain = float(jnp.real(jnp.sum(jnp.conj(grad_direct) * dA)))
p_conj = float(jnp.real(jnp.sum(grad_direct * dA)))
print()
print("=== pairing calibration (which contraction reproduces dE?) ===")
print(f"  finite difference        = {fd:.10f}")
print(f"  Re sum(conj(g) * dA)     = {p_plain:.10f}")
print(f"  Re sum(g * dA)           = {p_conj:.10f}")
use_conj = abs(p_plain - fd) <= abs(p_conj - fd)
print(f"  -> using {'Re<g, d> = Re sum(conj(g)*d)' if use_conj else 'Re sum(g*d)'}")


def pair(g, delta):
    return (
        jnp.real(jnp.sum(jnp.conj(g) * delta))
        if use_conj
        else jnp.real(jnp.sum(g * delta))
    )


# --- the adjoint solve, then cotangents on the frozen constants ----------
y_bar = (
    tilde_bar,
    tuple(jnp.zeros_like(x) for x in root_cov.u),
    S_bar,
    tuple(jnp.zeros_like(x) for x in root_cov.v),
)
_, vjp_y = jax.vjp(
    lambda y: M.asym_characteristic_residual_covariant(y, a_arr, root_cov, chi), y_star
)
F_bar, sresid = _solve_root_adjoint(
    lambda v: vjp_y(v)[0], y_bar, tol=1e-11, maxiter=800, restart=40
)
print(f"  adjoint solve residual   = {float(sresid):.3e}")


def F_of_consts(U_star, U_perp, Vh_star, Vh_perp, s_star_inv):
    c = root_cov._replace(
        U_star=U_star,
        U_perp=U_perp,
        Vh_star=Vh_star,
        Vh_perp=Vh_perp,
        s_star_inv=s_star_inv,
    )
    return M.asym_characteristic_residual_covariant(y_star, a_arr, c, chi)


_, vjp_c = jax.vjp(
    F_of_consts,
    root_cov.U_star,
    root_cov.U_perp,
    root_cov.Vh_star,
    root_cov.Vh_perp,
    root_cov.s_star_inv,
)
Ub, Upb, Vb, Vpb, sib = vjp_c(F_bar)


def dE_along_gauge(X):
    """dE/dt for the global gauge generated by anti-Hermitian X."""
    KX = jnp.kron(X, jnp.eye(d2, dtype=X.dtype))
    tot = 0.0
    for k in range(4):
        Us, Up = root_cov.U_star[k], root_cov.U_perp[k]
        Vs, Vp = root_cov.Vh_star[k], root_cov.Vh_perp[k]
        si = root_cov.s_star_inv[k]
        tot = tot + pair(Ub[k], Us @ X - KX @ Us)
        tot = tot + pair(Upb[k], -KX @ Up)
        tot = tot + pair(Vb[k], Vs @ KX - X @ Vs)
        tot = tot + pair(Vpb[k], Vp @ KX)
        tot = tot + pair(sib[k], si @ X - X @ si)
    return float(tot)


def dE_partial_only(X):
    """The same, but keeping only the `U* X` pieces -- the earlier (wrong) test."""
    tot = 0.0
    for k in range(4):
        tot = tot + pair(Ub[k], root_cov.U_star[k] @ X)
        tot = tot + pair(Vb[k], -X @ root_cov.Vh_star[k])
    return float(tot)


key = jax.random.PRNGKey(11)
scale = float(jnp.linalg.norm(grad_direct))
print()
print("=== dE/dt along the true gauge orbit (should vanish if Eq. 88 holds) ===")
worst_full = worst_part = 0.0
for i in range(8):
    key, sub = jax.random.split(key)
    G = jax.random.normal(sub, (chi, chi), dtype=jnp.complex128)
    X = 0.5 * (G - G.conj().T)  # anti-Hermitian
    X = X / jnp.linalg.norm(X)
    full, part = dE_along_gauge(X), dE_partial_only(X)
    worst_full, worst_part = max(worst_full, abs(full)), max(worst_part, abs(part))
    print(f"  X{i}: full law = {full:+.4e}    U*X-only = {part:+.4e}")
print()
print(f"  worst |dE/dt| full law   = {worst_full:.4e}")
print(f"  worst |dE/dt| U*X only   = {worst_part:.4e}   <- the earlier measurement")
print(f"  scale |grad_direct|      = {scale:.4e}")
print(f"  ratio (full law)         = {worst_full / scale:.3e}")


# ---------------------------------------------------------------------------
# Eq. 88 is fine, so check the linearisation point of d_p F: `F_of_p` rebuilds
# the double-layer array from A rather than reusing `a_arr`, and if the two
# disagree then d_p F is being taken at the wrong point.
# ---------------------------------------------------------------------------
def a_from_A(a_data):
    A_live = DenseTensor(a_data, A.indices)
    a_t = M._build_double_layer_tensor(A_live)
    labels = list(a_t.labels())
    perm = tuple(labels.index(lbl) for lbl in ("u2", "d2", "l2", "r2"))
    return a_t.transpose(perm).todense()


a_rebuilt = a_from_A(A_data)
print()
print("=== is d_p F linearised at the same point the root was found at? ===")
print(f"  |a_rebuilt - a_arr|      = {float(jnp.abs(a_rebuilt - a_arr).max()):.3e}")
print(f"  |a_arr|                  = {float(jnp.abs(a_arr).max()):.3e}")


def resid_norm(R):
    return float(jnp.sqrt(sum(jnp.sum(jnp.abs(x) ** 2) for x in jax.tree.leaves(R))))


F_at_aarr = M.asym_characteristic_residual_covariant(y_star, a_arr, root_cov, chi)
F_at_rebuilt = M.asym_characteristic_residual_covariant(
    y_star, a_rebuilt, root_cov, chi
)
print(f"  |F(y*, a_arr)|           = {resid_norm(F_at_aarr):.3e}")
print(f"  |F(y*, a_rebuilt)|       = {resid_norm(F_at_rebuilt):.3e}")

# ---------------------------------------------------------------------------
# Cross-check the assembly: adjoint route vs forward (JVP) route.  These are
# the same linear algebra, so disagreement means an assembly bug rather than a
# modelling assumption.
# ---------------------------------------------------------------------------
key2 = jax.random.PRNGKey(21)
dA2 = jax.random.normal(key2, A_data.shape, dtype=A_data.dtype)
dA2 = dA2 / jnp.linalg.norm(dA2)


def F_of_p(a_data):
    return M.asym_characteristic_residual_covariant(
        y_star, a_from_A(a_data), root_cov, chi
    )


_, vjp_p = jax.vjp(F_of_p, A_data)
adj_dir = float(pair(grad_direct - vjp_p(F_bar)[0], dA2))

# forward: solve d_y F . ydot = -(d_p F) dA2, then dE = d_p e . dA2 + d_y e . ydot
_, dF_dp = jax.jvp(F_of_p, (A_data,), (dA2,))
rhs = jax.tree.map(lambda x: -x, dF_dp)
_, jvp_y_lin = jax.linearize(
    lambda y: M.asym_characteristic_residual_covariant(y, a_arr, root_cov, chi), y_star
)
ydot, fresid = _solve_root_adjoint(jvp_y_lin, rhs, tol=1e-11, maxiter=800, restart=40)
fwd_dir = float(pair(grad_direct, dA2)) + float(
    sum(pair(b, d) for b, d in zip(jax.tree.leaves(y_bar), jax.tree.leaves(ydot)))
)
print()
print("=== adjoint route vs forward route (same linear algebra) ===")
print(f"  forward solve residual   = {float(fresid):.3e}")
print(f"  adjoint  <grad, dA>      = {adj_dir:+.10f}")
print(f"  forward  dE/dt           = {fwd_dir:+.10f}")
print(f"  difference               = {abs(adj_dir - fwd_dir):.3e}")
